<template>
  <div class="h-full flex flex-col">
    <!-- Upload section (only Charmante can upload) -->
    <div v-if="canUpload" class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5 mb-4 flex-shrink-0">
      <div class="flex items-center justify-between mb-2">
        <div>
          <p class="text-sm font-semibold text-gray-700 dark:text-gray-300">Weekly Attendance Report (IVM)</p>
          <p class="text-xs text-gray-500 dark:text-gray-400">Upload the file generated by IVM system</p>
        </div>
        <label class="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg text-sm font-medium cursor-pointer flex items-center gap-2">
          📎 Upload File
          <input type="file" class="hidden" accept=".csv,.xlsx,.xls,.pdf,.doc,.docx,.txt,.png,.jpg" @change="handleFileUpload" />
        </label>
      </div>
      <div v-if="uploading" class="mt-2 flex items-center gap-2 text-sm text-indigo-600 dark:text-indigo-400">
        <div class="animate-spin rounded-full h-4 w-4 border-2 border-indigo-500 border-t-transparent"></div>
        Uploading...
      </div>
      <div v-if="uploadSuccess" class="mt-2 text-sm text-green-600 dark:text-green-400">✅ File uploaded and HR has been notified</div>
      <div v-if="uploadErr" class="mt-2 text-sm text-red-600 dark:text-red-400">{{ uploadErr }}</div>
    </div>

    <!-- Filter -->
    <div class="flex items-center gap-3 mb-3 flex-shrink-0">
      <p class="text-xs text-gray-500 dark:text-gray-400 uppercase font-medium">Uploaded Reports</p>
      <DateFilter v-model:month="filterMonth" v-model:year="filterYear" />
    </div>

    <!-- Loading -->
    <div v-if="loading" class="flex-1 flex items-center justify-center">
      <div class="animate-spin rounded-full h-8 w-8 border-4 border-indigo-500 border-t-transparent"></div>
    </div>

    <!-- Files list -->
    <div v-else class="flex-1 overflow-auto">
      <div v-if="paginatedItems.length === 0" class="text-center py-12 text-gray-400 dark:text-gray-500">
        <p class="text-3xl mb-2">📄</p>
        <p class="text-sm">No attendance reports uploaded yet.</p>
      </div>
      <div v-else class="space-y-2">
        <div v-for="f in paginatedItems" :key="f.id"
          class="flex items-center justify-between bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl px-4 py-3 hover:shadow-sm transition-shadow">
          <div class="flex items-center gap-3 min-w-0">
            <span class="text-2xl">{{ fileIcon(f.fileName) }}</span>
            <div class="min-w-0">
              <p class="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">{{ f.fileName }}</p>
              <p class="text-xs text-gray-500 dark:text-gray-400">
                {{ formatDate(f.uploadedAt) }} · {{ formatFileSize(f.fileSizeBytes) }}
                <span v-if="f.uploadedByName"> · by {{ f.uploadedByName }}</span>
              </p>
            </div>
          </div>
          <div class="flex items-center gap-2 flex-shrink-0">
            <a :href="(import.meta.env.VITE_API_BASE_URL || '') + f.fileUrl" download
              class="px-3 py-1.5 text-xs bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 dark:text-indigo-400 rounded-lg hover:bg-indigo-100 dark:hover:bg-indigo-900/40 font-medium">
              ⬇️ Download
            </a>
          </div>
        </div>
      </div>
      <Pagination :page="page" :page-size="10" :total="total" @change="setPage" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import api from '@/api/axios';
import { useAuthStore } from '@/stores/auth.store';
import Pagination from '@/components/shared/Pagination.vue';
import DateFilter from '@/components/shared/DateFilter.vue';
import { usePagination } from '@/composables/usePagination';

const auth = useAuthStore();
const canUpload = computed(() => auth.user?.email === 'cumurungi9@gmail.com');

const loading = ref(true);
const uploading = ref(false);
const uploadSuccess = ref(false);
const uploadErr = ref('');
const uploadedFiles = ref<any[]>([]);

const { page, filterMonth, filterYear, total, paginatedItems, setPage } = usePagination(() => uploadedFiles.value, 10);

function formatDate(d: string) { return new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }); }
function formatFileSize(bytes: number) { if (bytes < 1024) return bytes + ' B'; if (bytes < 1024*1024) return (bytes/1024).toFixed(1) + ' KB'; return (bytes/(1024*1024)).toFixed(1) + ' MB'; }
function fileIcon(name: string) { if (name.endsWith('.pdf')) return '📕'; if (name.match(/\.xlsx?$/)) return '📊'; if (name.match(/\.(jpg|png|jpeg)$/)) return '🖼️'; return '📄'; }

async function handleFileUpload(event: Event) {
  const input = event.target as HTMLInputElement;
  if (!input.files?.length) return;
  uploading.value = true; uploadSuccess.value = false; uploadErr.value = '';
  const formData = new FormData();
  formData.append('file', input.files[0]);
  try {
    const { data } = await api.post('/hr/attendance/upload', formData);
    uploadedFiles.value.unshift(data);
    uploadSuccess.value = true;
    setTimeout(() => { uploadSuccess.value = false; }, 3000);
  } catch (e: any) { uploadErr.value = e.response?.data?.message || 'Upload failed'; }
  finally { uploading.value = false; input.value = ''; }
}

async function fetchUploadedFiles() {
  loading.value = true;
  try { const { data } = await api.get('/hr/attendance/files'); uploadedFiles.value = data; }
  catch (err) { console.error(err); }
  finally { loading.value = false; }
}

onMounted(fetchUploadedFiles);
</script>
